export const AircraftConstants = {
  ADD_AIRCRAFT: "ADD_AIRCRAFT",
  FETCH_AIRCRAFT_PENDING: "FETCH_AIRCRAFT_PENDING",
  TOGGLE_FETCH_AIRCRAFT_PENDING: "TOGGLE_FETCH_AIRCRAFT_PENDING",
  FETCH_AIRCRAFT: "FETCH_AIRCRAFT",
};
