export const AirportConstant = {
  ADD_AIRPORT: "ADD_AIRPORT",
  FETCH_AIRPORT_PENDING: "FETCH_AIRPORT_PENDING",
  TOGGLE_FETCH_AIRPORT_PENDING: "TOGGLE_FETCH_AIRPORT_PENDING",
  FETCH_AIRPORT: "FETCH_AIRPORT",
};
