export const TransactionConstant = {
  ADD_TRANSACTION: "ADD_TRANSACTION",
  FETCH_TRANSACTION_PENDING: "FETCH_TRANSACTION_PENDING",
  TOGGLE_FETCH_TRANSACTION_PENDING: "TOGGLE_FETCH_TRANSACTION_PENDING",
  FETCH_TRANSACTION: "FETCH_TRANSACTION",
};
